learning_rate: 0.0005
batch_size: 64
num_keep: 1024
experience_loop: 8
experience_replay: 64
lr_z: 0.1
beta: 50
mutation_rate: 0.067
population_size: 120
offspring_size: 70
reinitiation_interval: 10
rank_coefficient: 0.01
num_jobs: 1
penalty: rtb
valid_only: True
kl_coefficient: 0.01
starting_ga_from: 1000
use_novelty: True
update_during_ga: False