learning_rate: 0.0005
batch_size: 64
sigma: 500
experience_replay: 24
num_keep: 1024
mutation_rate: 0.067
population_size: 120
offspring_size: 70
reinitiation_interval: 1000
rank_coefficient: 0.01
num_jobs: 1
valid_only: False
starting_ga_from: 8000
use_novelty: False
update_during_ga: False
mating_rule: rank_based
novelty_measure: edge
top_p: 0.8
chromosome: node